[theme]
primaryColor = "#4f46e5"
backgroundColor = "white"
secondaryBackgroundColor = "#f6f7fb"
textColor = "#111827"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
