<<<<<<< HEAD
 [server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
=======
[server]
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "auto"
>>>>>>> desarollo
