# Configuración global para Streamlit Cloud
[browser]
# Desactiva la recolección de estadísticas de uso
gatherUsageStats = false 

[global]
# CRÍTICO: Deshabilita el menú principal de tres puntos, lo que oculta 'Share', 'Settings' 
# y la opción de 'View source file' (Ver código fuente).
showSidebarNavigation = false 

[client]
# Deshabilita el indicador de 'Rerunning' / 'Running' en la esquina inferior derecha 
# y el botón negro de 'Administrar la aplicación'.
displayEnabled = false 

[theme]
# Puedes personalizar el aspecto de la aplicación aquí (opcional)
primaryColor = "#4f46e5"
backgroundColor = "white"
secondaryBackgroundColor = "#f6f7fb"
textColor = "#111827"
font = "sans serif"
